In [1]:
import pandas as pd
import numpy as np
import seaborn as sns
import matplotlib.pyplot as plt

In [2]:
iris=pd.read_csv('Iris.csv',sep=',',header='infer')
iris

,Id,SepalLengthCm,SepalWidthCm,PetalLengthCm,PetalWidthCm,Species
0,1,5.1,3.5,1.4,0.2,Iris-setosa
1,2,4.9,3.0,1.4,0.2,Iris-setosa
2,3,4.7,3.2,1.3,0.2,Iris-setosa
3,4,4.6,3.1,1.5,0.2,Iris-setosa
4,5,5.0,3.6,1.4,0.2,Iris-setosa
...,...,...,...,...,...,...
145,146,6.7,3.0,5.2,2.3,Iris-virginica
146,147,6.3,2.5,5.0,1.9,Iris-virginica
147,148,6.5,3.0,5.2,2.0,Iris-virginica
148,149,6.2,3.4,5.4,2.3,Iris-virginica
149,150,5.9,3.0,5.1,1.8,Iris-virginica

In [3]:
iris1=iris.drop(['Id'],axis=1)

In [4]:
x=iris1.iloc[:,:4]
y=iris1.iloc[:,4:]

In [5]:
#splt into training and testing data
from sklearn.model_selection import train_test_split

In [6]:
x_train,x_test,y_train,y_test=train_test_split(x,y,test_size=0.30,random_state=4)

In [7]:
#USE KNN Classifier
from sklearn.neighbors import KNeighborsClassifier
knn=KNeighborsClassifier(n_neighbors=3)

In [8]:
#TRAIN KNN Classifier
knn.fit(x_train,y_train)

c:\Users\pat_p\anaconda3\lib\site-packages\sklearn\neighbors\_classification.py:179: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples,), for example using ravel().
  return self._fit(X, y)

KNeighborsClassifier(n_neighbors=3)

In [9]:
y_pred=knn.predict(x_test)
y_pred

array(['Iris-virginica', 'Iris-setosa', 'Iris-virginica',
       'Iris-virginica', 'Iris-virginica', 'Iris-versicolor',
       'Iris-virginica', 'Iris-setosa', 'Iris-setosa', 'Iris-virginica',
       'Iris-setosa', 'Iris-setosa', 'Iris-setosa', 'Iris-versicolor',
       'Iris-virginica', 'Iris-setosa', 'Iris-versicolor', 'Iris-setosa',
       'Iris-setosa', 'Iris-virginica', 'Iris-setosa', 'Iris-virginica',
       'Iris-versicolor', 'Iris-setosa', 'Iris-setosa', 'Iris-setosa',
       'Iris-setosa', 'Iris-setosa', 'Iris-setosa', 'Iris-virginica',
       'Iris-versicolor', 'Iris-setosa', 'Iris-virginica', 'Iris-setosa',
       'Iris-versicolor', 'Iris-virginica', 'Iris-virginica',
       'Iris-versicolor', 'Iris-versicolor', 'Iris-setosa',
       'Iris-virginica', 'Iris-setosa', 'Iris-versicolor', 'Iris-setosa',
       'Iris-virginica'], dtype=object)

In [10]:
y_test

             Species
128   Iris-virginica
18       Iris-setosa
130   Iris-virginica
105   Iris-virginica
107   Iris-virginica
78   Iris-versicolor
83   Iris-versicolor
14       Iris-setosa
5        Iris-setosa
133   Iris-virginica
25       Iris-setosa
11       Iris-setosa
12       Iris-setosa
63   Iris-versicolor
113   Iris-virginica
34       Iris-setosa
60   Iris-versicolor
2        Iris-setosa
24       Iris-setosa
123   Iris-virginica
35       Iris-setosa
124   Iris-virginica
68   Iris-versicolor
26       Iris-setosa
29       Iris-setosa
19       Iris-setosa
41       Iris-setosa
16       Iris-setosa
20       Iris-setosa
101   Iris-virginica
84   Iris-versicolor
47       Iris-setosa
108   Iris-virginica
1        Iris-setosa
93   Iris-versicolor
144   Iris-virginica
125   Iris-virginica
92   Iris-versicolor
86   Iris-versicolor
46       Iris-setosa
135   Iris-virginica
7        Iris-setosa
65   Iris-versicolor
10       Iris-setosa
132   Iris-virginica

In [11]:
#CHECK Accuracy Score
from sklearn.metrics import accuracy_score
accuracy_score(y_test,y_pred)

0.9777777777777777